// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registory

import (
	"github.com/KETAKOM/go-study-app/application/foobarbaz"
)

// Injectors from injecter.go:

func InitializeBaz() (foobarbaz.Baz, error) {
	foo := foobarbaz.ProvideFoo()
	bar := foobarbaz.ProvideBar(foo)
	baz, err := foobarbaz.ProvideBaz(bar)
	if err != nil {
		return foobarbaz.Baz{}, err
	}
	return baz, nil
}
