// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package sample

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SampleRequest struct {
	Sample               string   `protobuf:"bytes,1,opt,name=sample,proto3" json:"sample,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleRequest) Reset()         { *m = SampleRequest{} }
func (m *SampleRequest) String() string { return proto.CompactTextString(m) }
func (*SampleRequest) ProtoMessage()    {}
func (*SampleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *SampleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleRequest.Unmarshal(m, b)
}
func (m *SampleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleRequest.Marshal(b, m, deterministic)
}
func (m *SampleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleRequest.Merge(m, src)
}
func (m *SampleRequest) XXX_Size() int {
	return xxx_messageInfo_SampleRequest.Size(m)
}
func (m *SampleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SampleRequest proto.InternalMessageInfo

func (m *SampleRequest) GetSample() string {
	if m != nil {
		return m.Sample
	}
	return ""
}

type SampleResponce struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleResponce) Reset()         { *m = SampleResponce{} }
func (m *SampleResponce) String() string { return proto.CompactTextString(m) }
func (*SampleResponce) ProtoMessage()    {}
func (*SampleResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{1}
}

func (m *SampleResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleResponce.Unmarshal(m, b)
}
func (m *SampleResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleResponce.Marshal(b, m, deterministic)
}
func (m *SampleResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleResponce.Merge(m, src)
}
func (m *SampleResponce) XXX_Size() int {
	return xxx_messageInfo_SampleResponce.Size(m)
}
func (m *SampleResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleResponce.DiscardUnknown(m)
}

var xxx_messageInfo_SampleResponce proto.InternalMessageInfo

func (m *SampleResponce) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleRequest)(nil), "sample.SampleRequest")
	proto.RegisterType((*SampleResponce)(nil), "sample.SampleResponce")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0) }

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xd4, 0xb9, 0x78,
	0x83, 0xc1, 0xac, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xa8, 0x94, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x4c, 0xa1, 0x12, 0x17, 0x1f, 0x4c, 0x61, 0x71, 0x41, 0x7e,
	0x5e, 0x72, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x51, 0x6a, 0x31, 0x54, 0x19, 0x88, 0x69, 0xe4, 0xc2,
	0xc5, 0x06, 0x51, 0x23, 0x64, 0xc5, 0xc5, 0xe9, 0x9e, 0x5a, 0x02, 0xe5, 0x88, 0xea, 0x41, 0xad,
	0x46, 0xb1, 0x49, 0x4a, 0x0c, 0x5d, 0x18, 0x62, 0x6e, 0x12, 0x1b, 0xd8, 0x85, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x92, 0x91, 0x7f, 0x5b, 0xb1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SampleClient is the client API for Sample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SampleClient interface {
	GetSample(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponce, error)
}

type sampleClient struct {
	cc *grpc.ClientConn
}

func NewSampleClient(cc *grpc.ClientConn) SampleClient {
	return &sampleClient{cc}
}

func (c *sampleClient) GetSample(ctx context.Context, in *SampleRequest, opts ...grpc.CallOption) (*SampleResponce, error) {
	out := new(SampleResponce)
	err := c.cc.Invoke(ctx, "/sample.Sample/GetSample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServer is the server API for Sample service.
type SampleServer interface {
	GetSample(context.Context, *SampleRequest) (*SampleResponce, error)
}

// UnimplementedSampleServer can be embedded to have forward compatible implementations.
type UnimplementedSampleServer struct {
}

func (*UnimplementedSampleServer) GetSample(ctx context.Context, req *SampleRequest) (*SampleResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSample not implemented")
}

func RegisterSampleServer(s *grpc.Server, srv SampleServer) {
	s.RegisterService(&_Sample_serviceDesc, srv)
}

func _Sample_GetSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServer).GetSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.Sample/GetSample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServer).GetSample(ctx, req.(*SampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample.Sample",
	HandlerType: (*SampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSample",
			Handler:    _Sample_GetSample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}
